name: Deploy API to AWS

on:
  workflow_run:
    workflows: ["Test Conda Environment"]
    branches: [ main ]
    types:
      - in_progress
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker build -t job_search_helper:latest -f docker/api.dockerfile .
      - run: docker tag job_search_helper ${{ secrets.DOCKER_USERNAME }}/job_search_helper:latest
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/job_search_helper:latest
      - name: Deploy to AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            sudo export $PORT=5000
            sudo echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/job_search_helper:latest
            sudo docker stop job_search_helper
            sudo docker rm job_search_helper
            sudo docker run -d --name job_search_helper -p $PORT:$PORT ${{ secrets.DOCKER_USERNAME }}/job_search_helper:latest
