name: Test Conda Environment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Install dependencies
      run: |
        echo: "Setting up environment"
        conda env create -f environment.yml
        conda activate project-environment
    - name: lint
      run: |
        echo "Running lint"
        pylint src/
    - name: Run tests
      run: |
        echo "Running tests"
        pytest src/tests/

