name: Test Conda Environment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
    - name: Install dependencies
      run: |
        conda env create -f environment.yml
        conda activate project-environment
    - name: lint
      run: |
        pylint src/
    - name: Run tests
      run: |
        pytest src/tests/

